FROM emscripten/emsdk:3.1.7 AS build_wasm
ARG NB_CORES=1
LABEL org.opencontainers.image.source https://github.com/Intlekt/dockers-config/pulls

RUN apt-get update && apt-get install -y default-jre git
